
(:label accm  :source-types entity            :dest-type entity          :desc "accompaniment - links [ENTITY:*x] to [ENTITY:*y], where *y is accopanying *x")
(:label agnt  :source-types act               :dest-type animate         :desc "agent - links [ACT] to [ANIMATE], where [ANIMATE] is the actor of the [ACT]")
(:label arg   :source-types function          :dest-type data            :desc "argument - identifies the argument of a function")
(:label attr  :source-types entity            :dest-type attribute       :desc "attribute - links [ENTITY:*x] to [ATTRIBUTE:*y], where *x has an attribute *y")
(:label betw  :source-types (entity entity)   :dest-type entity          :desc "between - links [ENTITY:*x] to [ENTITY:*y] and [ENTITY:*z], where *x is between entities *y and *z")
(:label caus  :source-types state             :dest-type state           :desc "cause - links [STATE:*x] to [STATE:*y], where *y is a cause of *x")
(:label chld  :source-types person            :dest-type person          :desc "child - links [PERSON:*x] to [PERSON:*y], where *x has child *y")
(:label chrc  :source-types entity            :dest-type characteristic  :desc "characteristic - links [ENTITY:*x] to [ENTITY:*y], where *x has the characteristic *y")
(:label comp  :source-types entity            :dest-type entity          :desc "comparison"     )
(:label cons  :source-types entity            :dest-type substance       :desc "constituent - indicates the substance is a constittuent of the entity")
(:label cont  :source-types entity            :dest-type entity          :desc "content - links [ENTITY:*x] to [ENTITY:*y], where *x has content *y")
(:label dest  :source-types act               :dest-type place           :desc "destination - links [ACT] to [PLACE], where the act is directed toward place")
(:label dur   :source-types state             :dest-type time-period     :desc "duration - links [STATE] to [TIME-PERIOD], where time-period is the aomint of time that state exists")
(:label expr  :source-types state             :dest-type animate         :desc "experiencer - links [STATE] to [ANIMATE], where animate is experiencing the state")
(:label freq  :source-types event             :dest-type time-period     :desc "frequency - links [EVENT] to a set of [TIME-PERIOD], indicating when the event occurs , eg. 'weekly'")
(:label init  :source-types act               :dest-type animate         :desc "initiator - links [ACT] to [ANIMATE], where asnimate starts an act occurring")
(:label inst  :source-types act               :dest-type entity          :desc "instrument - links [ENTITY] to [ACT], where entity is causally involved in the act")
(:label link  :source-types t                 :dest-type t               :desc "link - links two things")
(:label loc   :source-types t                 :dest-type place           :desc "location - links anything to its location")
(:label manr  :source-types act               :dest-type attribute       :desc "manner - links an [ACT] to an [ATTRIBUTE] of the act")
(:label matr  :source-types entity            :dest-type substance       :desc "material - indicates the entity is made from the material")
(:label meas  :source-types dimension         :dest-type measure         :desc "measure - indicates the measure (eg. lenght, weight) of a dimension")
(:label memb  :source-types set               :dest-type entity          :desc "member - a->(name)->b; a has b as a member")
(:label meth  :source-types act               :dest-type situation       :desc "method - ??")
(:label name  :source-types entity            :dest-type word            :desc "name - a->(name)->b; The word (type b) is called the NAME of (referent a)")
(:label necs  :source-types t                 :dest-type proposition     :desc "necessary - monadic; links to a [PROPOSITION] which is necessarily true")
(:label neg   :source-types t                 :dest-type proposition     :desc "negation - monadic; links to a [PROPOSITION] which is asserted to be false")
(:label obj   :source-types act               :dest-type entity          :desc "object - links an [ACT] to an [ENTITY], which is acted upon")
(:label on    :source-types entity            :dest-type entity          :desc "on - links [ENTITY:*x] to [ENTITY:*y], where *x is on *y")
(:label part  :source-types entity            :dest-type entity          :desc "part - links [ENTITY:*x] to [ENTITY:*y], where *x has part *y")
(:label past  :source-types nil               :dest-type proposition     :desc "past - monadic; links to a [PROPOSITION] that was true before present time")
(:label path  :source-types act               :dest-type place           :desc "path - links [ACT] to a set of [PLACE],")
(:label poss  :source-types animate           :dest-type entity          :desc "possession - indicating the animate object possesses the entity")
(:label psbl  :source-types t                 :dest-type proposition     :desc "possible - monadic; links to a [PROPOSITION] which is possibly true")
(:label ptim  :source-types t                 :dest-type time            :desc "point-in-time - indicates when a proposition occurs")
(:label qty   :source-types entity            :dest-type number          :desc "quantity - links a set  of ENTITY{*} to a number indicating the number of entities")
(:label rcpt  :source-types act               :dest-type animate         :desc "recipient - indicates the animate which receives the object or result of the act")
(:label prod  :source-types act               :dest-type entity          :desc "product - links an [ACT] to an [ENTITY] pproduced by the act")
(:label rslt  :source-types act               :dest-type state           :desc "result - links an [ACT] to an [STATE] that results from the act")
(:label site  :source-types event             :dest-type place           :desc "site - links an event to its location")
(:label srce  :source-types act               :dest-type entity          :desc "source - indicates the source of the entity ")
(:label stat  :source-types entity            :dest-type state           :desc "state - indicates the state of an entity")
(:label succ  :source-types t                 :dest-type t               :desc "successor - indicates that the destination thing follows the source thing")
(:label supp  :source-types entity            :dest-type entity          :desc "support - links [ENTITY:*x] to [ENTITY:*y], where *x has support *y")
(:label thme  :source-types entity            :dest-type subject-matter  :desc "theme - associates some [SUBJECT-MATTER] with an [ENTITY]")
(:label untl  :source-types state             :dest-type time            :desc "until - indicates the time when a state ceases to exist")
