
(:label act :supertypes (event) :cgraph "[act]->(agnt)->[animate].")
(:label age :supertypes (characteristic) :cgraph "[age]-(chrc)->[entity] (dur)->[time-period].")
(:label angel :supertypes (animate mobile-entity ~physobj))
(:label animal :supertypes (animate mobile-entity ~machine))
(:label animate :supertypes (entity))
(:label arrive :supertypes (act) :cgraph "[arrive]-(agnt)->[mobile-entity] (loc)->[place].")
(:label attribute :supertypes (T) :cgraph "[attribute]<-(attr)<-[entity].")
(:label automobile :supertypes (conveyance))
(:label bar :supertypes (physobj))
(:label bus :supertypes (conveyance))
(:label believe :supertypes (state) :cgraph "[believe]-(expr)->[animate] (obj)->[proposition].")
(:label buick :supertypes (automobile))
(:label building :supertypes (place))
(:label cake :supertypes (food))
(:label cake-stuff :supertypes (food stuff) :cgraph "[cake-stuff]<-matr)<-[cake].")
(:label cat :supertypes (animal))
(:label characteristic :supertypes (attribute))
(:label chevy :supertypes (automobile))
(:label child :supertypes (person) :cgraph "[child]<-(chld)<-[parent].")
(:label city :supertypes (place society))
(:label clothing :supertypes (stuff))
(:label color :supertypes (attribute) :cgraph "[color]<-(attr)<-[physobj].")
(:label command :supertypes (message) :cgraph "[command]-(obj)->[order]->(rcpt)->[person].")
(:label communicate :supertypes (give) :cgraph "[communicate]-(agnt)->[animate] (inst)->[entity] (rcpt)->[animate] (obj)->[information].")
(:label compliment :supertypes (communicate))
(:label contain :supertypes (state) :cgraph "[contain]- (loc)->[entity:*x]->(part)->[interior:*z] (obj)->[entity:*y]->(loc)->[interior:*z].")
(:label conveyance :supertypes (mobile-entity))
(:label cut :supertypes (act) :cgraph "[cut]-(agnt)->[animate] (rcpt)->[animate] (obj)->[entity].")
(:label data :supertypes (information) :cgraph "[data]<-(arg)<-[function].")
(:label difficult :supertypes (manner) :cgraph "[difficult]-(expr)->[animate] (manr)<-[act].")
(:label dimension :supertypes (length))
(:label dog :supertypes (animal))
(:label drive :supertypes (act))
(:label eat :supertypes (act) :cgraph "[eat]-(agnt)->[animate] (obj)->[food] (manr)->[manner].")
(:label elephant :supertypes (animal))
(:label employee :supertypes (person))
(:label entity :supertypes (T))
(:label event :supertypes (T))
(:label fast :supertypes (manner))
(:label food :supertypes (entity physobj) :cgraph "[food]<-(obj)<-[eat].")
(:label function :supertypes (information) :cgraph "[function]->(arg)->[data].")
(:label funding-request :supertypes (request-act))
(:label girl :supertypes (person))
(:label give :supertypes (act) :cgraph "[give]-(agnt)->[animate] (rcpt)->[animate] (obj)->[entity].")
(:label go :supertypes (act))
(:label hardness :supertypes (characteristic) :cgraph "[hardness]<-(attr)<-[physobj].")
(:label hard :supertypes (hardness))
(:label soft :supertypes (hardness))
(:label hardware :supertypes (stuff))
(:label homework :supertypes (work))
(:label human :supertypes (animal))
(:label information :supertypes (T))
(:label interior :supertypes (entity) :cgraph "[interior]<-(part)<-[entity].")
(:label jack :supertypes (tool))
(:label kitchen :supertypes (room))
(:label know :supertypes (state) :cgraph "[know]-(expr)->[animate] (stat)->[proposition].")
(:label lay :supertypes (act) :cgraph "[lay]->(agnt)->[aqnimate] (stat)->[physobj] (loc)->[place].")
(:label length :supertypes (measure))
(:label love :supertypes (state) :cgraph "[love]-(expr)->[animate] (obj)->[entity].")
(:label machine :supertypes (tool))
(:label make :supertypes (act) :cgraph "[make]-(agnt)->[animate] (matr)->[substance] (rslt)->[physobj].")
(:label manner :supertypes (characteristic))
(:label mat :supertypes (physobj place))
(:label measure :supertypes (characteristic))
(:label message :supertypes (information) :cgraph "[message]<-(obj)<-[communicate].")
(:label mobile-entity :supertypes (physobj))
(:label monkey :supertypes (animal))
(:label number :supertypes (T))
(:label old :supertypes (age))
(:label order :supertypes (communicate))
(:label parent :supertypes (person) :cgraph "[parent]->(chld)->[child].")
(:label person :supertypes (animal))
(:label pet :supertypes (animal) :cgraph "[pet]<-(poss)<-[person].")
(:label physobj :supertypes (entity))
(:label pie :supertypes (food))
(:label place :supertypes (stationary-entity) :cgraph "[place]<-(loc)<-[t].")
(:label process :supertypes (T))
(:label proposition :supertypes (information))
(:label receive :supertypes (act) :cgraph "[receive]-(rcpt)->[animate] (inst)->[entity] (obj)->[entity] (srce)->[place].")
(:label request :supertypes (message) :cgraph "[request]<-(obj)<-[communicate].")
(:label request-act :supertypes (act) :cgraph "[request-act]- (agnt)->[animate] (obj)->[request].")
(:label robot :supertypes (animate machine mobile-entity))
(:label rock :supertypes (substance))
(:label room :supertypes (place) :cgraph "[room]<-(part)<-[building].")
(:label safe :supertypes (state))
(:label shell :supertypes (substance))
(:label set :supertypes (act) :cgraph "[set]- (agnt)->[animate] (stat)->[physobj] (loc)->[place].")
(:label sit :supertypes (state) :cgraph "[sit]- (agnt)->[animate] (stat)->[physobj] (loc)->[place].")
(:label situation :supertypes (state)  )
(:label society :supertypes (T))
(:label species :supertypes (information))
(:label spoon :supertypes (utensil))
(:label state :supertypes (T))
(:label stationary-entity :supertypes (entity))
(:label stuff :supertypes (entity))
(:label subject-matter :supertypes (information))
(:label substance :supertypes (entity))
(:label T)
(:label talk :supertypes (act))
(:label teach :supertypes (act) :cgraph "[teach]-(agnt)->[animate] (rcpt)->[animate] (obj)->[subject-matter].")
(:label teacher :supertypes (person) :cgraph "[teacher]<-(agnt)<-[teach]-(rcpt)->[animate] (obj)->[subject-matter].")
(:label telephone :supertypes (physobj) :cgraph "[telephone]<-(inst)<-[communicate].")
(:label temperature :supertypes (measure))
(:label think :supertypes (act) :cgraph "[think]-(agnt)->[animate] (obj)->[proposition].")
(:label thought :supertypes (proposition) :cgraph "[thought]<-(obj)<-[think].")
(:label time :supertypes (number))
(:label time-period :supertypes (length))
(:label tool :supertypes (entity) :cgraph "[tool]<-(inst)<-[act].")
(:label transport :supertypes (process))
(:label use :supertypes (act) :cgraph "[use]- (agnt)->[animate] (inst)->[entity].")
(:label utensil :supertypes (tool))
(:label walk :supertypes (act))
(:label walnut :supertypes (food))
(:label warm :supertypes (state) :cgraph "[warm]- (expr)->[animal] (inst)->[~animate] (loc)->[place] (ptim)->[time].")
(:label wear :supertypes (act) :cgraph "[wear]-(obj)->[clothing] (agnt)->[human].")
(:label wear-out :supertypes (process) :cgraph "[wear-out]-(obj)->[physobj] (inst)->[tool].")
(:label word :supertypes (information))
(:label work :supertypes (act))
(:label young :supertypes (age))
