

(:label abstract :supertypes (entity))
(:label abstract-object :supertypes (abstract))
(:label act :supertypes (event) :canonical-graph "[ACT]→(agnt)→[ANIMATE].")
(:label activity-type :supertypes (abstract-object))
(:label adult :supertypes (person) :canonical-graph "[ADULT]- (life-stage)→[ADULTHOOD]")
(:label adulthood :supertypes (life-stage) :canonical-graph "[ADULTHOOD]- (thme)→[PERSON]")
(:label age :supertypes (temporal-attribute))
(:label ancient :supertypes (age))
(:label angel :supertypes (animate ))
(:label animal :supertypes (animate))
(:label animate :supertypes (physical))
(:label areal-extent :supertypes (spatial-extent))
(:label attend :supertypes (act))
(:label attribute :supertypes (quality) :canonical-graph "[ATTRIBUTE]←(attr)←[ENTITY].")
(:label automobile :supertypes (vehicle))
(:label bag :supertypes (collection))
(:label bark :supertypes (communicate))
(:label belief :supertypes (state) :canonical-graph "[BELIEF]→(expr)→[ANIMATE]." :graph-compatible t)
(:label body-part :supertypes (physical))
(:label book :supertypes (object information))
(:label boy :supertypes (child) :canonical-graph "[BOY]- (sex)→[MALE] (life-stage)→[CHILDHOOD]")
(:label breakfast :supertypes (meal-food))
(:label breakfast-event :supertypes (meal) :canonical-graph "[BREAKFAST-EVENT]→(has-part)→[EAT]- (agnt)→[PERSON] (obj)→[breakfast]")
(:label cake :supertypes (food))
(:label carefully :supertypes (manner))
(:label carry :supertypes (move))
(:label cat :supertypes (animal))
(:label characteristic :supertypes (⊤))
(:label chevy-vehicle :supertypes (automobile))
(:label child :supertypes (person) :canonical-graph "[CHILD]- (life-stage)→[CHILDHOOD]")
(:label childhood :supertypes (life-stage) :canonical-graph "[CHILDHOOD]- (thme)→[PERSON]")
(:label city :supertypes (place))
(:label city-government :supertypes (society)  :supertypes "[CITY-GOVERNMENT]←(agnt)←[GOVERN]→(ptnt)→[CITY]")
(:label collection :supertypes (abstract-object))
(:label communicate :supertypes (give))
(:label complexity :supertypes (evaluative-attribute))
(:label currency :supertypes (inanimate))
(:label desire :supertypes (state) :canonical-graph "[DESIRE]→(expr)→[ANIMATE]")
(:label difficulty :supertypes (evaluative-attribute))
(:label dinner :supertypes (meal-food))
(:label dinner-event :supertypes (meal) :canonical-graph "[DINNER-EVENT]- (has-part)→[EAT]-(agnt)→[PERSON: *x] (obj)→[dinner], (has-part)→[ATTEND]→(agnt)→[PERSON: *x]")
(:label distance :supertypes (length) :canonical-graph "[DISTANCE]- (from)←[ENTITY] (to)←[ENTITY]")
(:label dog :supertypes (animal))
(:label drink :supertypes (ingest))
(:label drive :supertypes (transport))
(:label duration :supertypes (temporal-extent) :canonical-graph "[DURATION]←(attr)←[SITUATION]")
(:label easy :supertypes (difficulty))
(:label eat :supertypes (ingest))
(:label end-time :supertypes (time-stamp))
(:label entity :supertypes (individual))
(:label evaluative-attribute :supertypes (attribute))
(:label event :supertypes (situation))
(:label extent :supertypes (measure))
(:label fast :supertypes (speed))
(:label female :supertypes (attribute))
(:label fly :supertypes (transport))
(:label food :supertypes (substance))
(:label food-item :supertypes (object))
(:label ford-vehicle :supertypes (automobile))
(:label girl :supertypes (child) :canonical-graph "[GIRL]- (sex)→[FEMALE] (life-stage)→[CHILDHOOD]")
(:label give :supertypes (act) :canonical-graph "[GIVE]- (agnt)→[ANIMATE] (obj)→[ENTITY] (rcpt)→[ANIMATE]")
(:label hard :supertypes (hardness))
(:label hardness :supertypes (physical-attribute))
(:label heap :supertypes (collection))
(:label inanimate :supertypes (physical))
(:label individual :supertypes (⊤))
(:label inform :supertypes (communicate) :canonical-graph "[INFORM]- (agnt)→[ANIMATE] (inst)→[ENTITY] (rcpt)→[ANIMATE] (obj)→[INFORMATION].")
(:label information :supertypes (abstract-object))
(:label ingest :supertypes (act) :canonical-graph "[INGEST]-(agnt)→[ANIMATE](obj)→[SUBSTANCE](dest)→[BODY-PART]")
(:label intention :supertypes (state) :canonical-graph "[INTENTION]- (expr)→[ANIMATE] (goal)→[SITUATION]")
(:label know :supertypes (state) :canonical-graph "[KNOW]- (expr)→[ANIMATE] (stat)→[PROPOSITION].")
(:label length :supertypes (linear-extent))
(:label life-stage :supertypes (state))
(:label linear-extent :supertypes (spatial-extent))
(:label list :supertypes (collection))
(:label lunch :supertypes (meal-food))
(:label lunch-event :supertypes (meal) :canonical-graph "[LUNCH-EVENT]]→(has-part)→[EAT]- (agnt)→[PERSON] (obj)→[LUNCH]")
(:label machine :supertypes (tool))
(:label male :supertypes (attribute))
(:label man :supertypes (adult) :canonical-graph "[MAN]- (sex)→[MALE] (life-stage)→[ADULTHOOD]")
(:label manner :supertypes (attribute characteristic))
(:label mass :supertypes (measure))
(:label mat :supertypes (place))
(:label meal :supertypes (event))
(:label meal-food :supertypes (food))
(:label measure :supertypes (quality))
(:label monkey :supertypes (animal))
(:label move :supertypes (act))
(:label news :supertypes (information))
(:label noisy :supertypes (attribute))
(:label number :supertypes (quality))
(:label object :supertypes (inanimate))
(:label object-transfer :supertypes (give))
(:label old :supertypes (age))
(:label organization :supertypes (animate))
(:label person :supertypes (animate))
(:label pet :supertypes (animal))
(:label pet-owner :supertypes (person) :definition "[PERSON: *lambda]->(poss)->[PET]")
(:label physical :supertypes (entity))
(:label physical-attribute :supertypes (attribute))
(:label pick-up :supertypes (act))
(:label pie :supertypes (food))
(:label place :supertypes (inanimate) :canonical-graph "[PLACE]←(loc)←[⊤].")
(:label proposition :supertypes (abstract-object) :graph-compatible t)
(:label push :supertypes (move))
(:label quality :supertypes (abstract))
(:label quickly :supertypes (manner))
(:label quietly :supertypes (manner))
(:label robot :supertypes (animate machine animate))
(:label rock :supertypes (object))
(:label rough :supertypes (texture))
(:label see :supertypes (act) :canonical-graph "[SEE]- (agnt)→[ANIMATE] (obj)→[ENTITY] (inst)→[OBJECT]")
(:label sell :supertypes (give) :canonical-graph "[SELL]- (agnt)→[ANIMATE] (obj)→[ENTITY] (inst)→[CURRENCY] (rcpt)→[ANIMATE]")
(:label sequence :supertypes (collection))
(:label set :supertypes (collection))
(:label shell :supertypes (substance))
(:label simple :supertypes (complexity))
(:label sit :supertypes (act))
(:label situation :supertypes (individual) :graph-compatible t)
(:label size :supertypes (physical-attribute))
(:label slow :supertypes (speed))
(:label smooth :supertypes (texture))
(:label society :supertypes (organization))
(:label soft :supertypes (hardness))
(:label spatial-extent :supertypes (extent))
(:label speed :supertypes (physical-attribute))
(:label spoon :supertypes (object))
(:label start-time :supertypes (time-stamp))
(:label state :supertypes (situation))
(:label substance :supertypes (inanimate))
(:label swallow :supertypes (ingest))
(:label task :supertypes (activity-type))
(:label telephone :supertypes (object))
(:label temperature :supertypes (measure))
(:label temporal-attribute :supertypes (attribute))
(:label temporal-extent :supertypes (extent))
(:label tesla-vehicle :supertypes (automobile))
(:label texture :supertypes (physical-attribute))
(:label think :supertypes (act))
(:label time-period :supertypes (abstract-object) :canonical-graph "[TIME-PERIOD]- (attr)→[START-TIME] (attr)→[END-TIME]")
(:label time-stamp :supertypes (temporal-attribute))
(:label telescope :supertypes (tool))
(:label tool :supertypes (entity))
(:label transfer :supertypes (give) :canonical-graph "[TRANSFER]- (agnt)→[ANIMATE] (obj)→[PHYSICAL] (inst)→[PHYSICAL] (rcpt)→[ANIMATE]")
(:label transport :supertypes (move))
(:label vehicle :supertypes (object))
(:label volumetric-extent :supertypes (spatial-extent))
(:label walnut  :supertypes (food))
(:label wish  :supertypes (desire) :canonical-graph "[WISH]- (expr)→[ANIMATE] (thme)→[ENTITY]")
(:label woman :supertypes (adult) :canonical-graph "[WOMAN]- (sex)→[FEMALE] (life-stage)→[ADULTHOOD]")
(:label young :supertypes (age))
