
(:label age   :source-types physical          :dest-type age             :desc "age - links [PHYSICAL] to [AGE], indicating the age of the physical thing")
(:label agnt  :source-types act               :dest-type animate         :desc "agent - links [ACT] to [ANIMATE], where [ANIMATE] is the actor of the [ACT]")
(:label attr  :source-types entity            :dest-type attribute       :desc "attribute - links [ENTITY:*x] to [ATTRIBUTE:*y], where *x has an attribute *y")
(:label chrc  :source-types entity            :dest-type attribute       :desc "characteristic")
(:label cntns :source-types entity            :dest-type entity          :desc "contains")
(:label dest  :source-types event             :dest-type place           :desc "destination - links [ACT] to [PLACE], where the act is directed toward place")
(:label dur   :source-types situation         :dest-type duration        :desc "duration - links [SITUATION] to [DURATION], where duration is the amount of time the situation exists")
(:label elem  :source-types sequence          :dest-type number          :desc "element")
(:label expr  :source-types state             :dest-type animate         :desc "experiencer - links [STATE] to [ANIMATE], where animate is experiencing the state")
(:label from  :source-types entity            :dest-type entity          :desc "from - provides an ordering between two concepts, indicates an initial concept")
(:label goal  :source-types state             :dest-type situation       :desc "goal - the situation a mental state is directed toward")
(:label has-part  :source-types individual    :dest-type individual      :desc "life stage")
(:label hgt   :source-types physical          :dest-type distance        :desc "height - links [PHYSICAL] to [DISTANCE], where distance is the height of the physical object")
(:label init  :source-types act               :dest-type animate)
(:label inst  :source-types event             :dest-type entity          :desc "instrument - links [ENTITY] to [EVENT], where entity is causally involved in the act")
(:label life-stage  :source-types person      :dest-type life-stage      :desc "life stage")
(:label loc   :source-types ⊤                 :dest-type place           :desc "location - links anything to its place")
(:label manr  :source-types act               :dest-type manner          :desc "manner - links an [ACT] to an [ATTRIBUTE] of the act")
(:label matr  :source-types entity            :dest-type substance       :desc "material")
(:label membr :source-types set               :dest-type entity          :desc "member - set has member enttity")
(:label obj   :source-types act               :dest-type entity          :desc "object - links an [ACT] to an [ENTITY], which is acted upon")
(:label on    :source-types entity            :dest-type entity          :desc "on - links [ENTITY:*x] to [ENTITY:*y], where *x is on *y")
(:label part  :source-types object            :dest-type entity          :desc "part - object has part  entity")
(:label ploc  :source-types physical          :dest-type place           :desc "physical location - links an object to its place")
(:label poss  :source-types animate           :dest-type entity          :desc "possession - indicating the animate object possesses the entity")
(:label psize :source-types physical          :dest-type size            :desc "physical size - the number of members in a set or collection")
(:label ptnt  :source-types act               :dest-type entity          :desc "patient")
(:label rcpt  :source-types act               :dest-type animate         :desc "recipient - indicates the animate which receives the object or result of the act")
(:label rslt  :source-types act               :dest-type state           :desc "result - the condition that obtains after an act")
(:label sex   :source-types animate           :dest-type attribute       :desc "sex")
(:label size  :source-types collection        :dest-type number          :desc "size - the number of members in a collection")
(:label stat  :source-types state             :dest-type proposition     :desc "statement/content - links [ENTITY] with a [SITUATION]")
(:label temp  :source-types physical          :dest-type temperature     :desc "temperature - links [PHYSICAL] to [TEMPERATURE], where temperature is the temperature of the physical object")
(:label thme  :source-types situation         :dest-type entity          :desc "theme - associates some [ENTITY] with a [SITUATION]")
(:label to    :source-types entity            :dest-type entity          :desc "to - provides an ordering between two concepts, indicates a terminating concept")
(:label wgt   :source-types physical          :dest-type mass            :desc "weight - links [PHYSICAL] to [MASS], where mass is the weight of the physical object")


(:label governs :source-types society          :dest-type place            :desc "governs")
