
(in-package :cgraph)

;;; uses graphviz
;;; https://graphviz.gitlab.io
;;; requires installation of graphviz-dot-mode
;;; https://ppareit.github.io/graphviz-dot-mode
;;; https://raw.github.com/ppareit/graphviz-dot-mode/master/graphviz-dot-mode.el
;;; https://github.com/ppareit/graphviz-dot-mode

(defparameter *slot-alignment* "center")
(defparameter *slot-name-prefix* ":")

(defun type-traversal (type-name
                       visited
                       &key
                         (parents t)
                         (children t)
                         (std-and-t nil))

  (let ((ctype (get-concept-type type-name)))
    (unless (gethash ctype visited)
      (setf (gethash ctype visited) t)
      (when children
        (dolist (i (direct-subtypes ctype))
          (type-traversal i visited :parents nil :std-and-t std-and-t)))
      (when parents
        (dolist (i (direct-supertypes ctype))
          (unless (and (not std-and-t)
                       (or (eql i 'T)
                           (eql i 'STANDARD-OBJECT)))
            (type-traversal i visited :children nil :std-and-t std-and-t))))))
  visited)


(defun make-type-record (type-name      ; symbol
                         &key
                           (color "#FFFF99"))
  (let* ((rec (format nil
                      "~A    <TR><TD BGCOLOR=\"~A\"><FONT FACE=\"Arial Bold\">~A</FONT></TD></TR>~%"
                      "" color type-name)))
    #+nil

    (setf rec
          (concatenate 'string rec
                       (format nil "    <TR><TD align=\"~a\"><FONT FACE=\"Arial\">~a~A</FONT></TD></TR>~%"
			       *slot-alignment* *slot-name-prefix* "")))
    rec))


(defun generate-concept-type-digraph (&key (type-name-list (list 't))
                                           (stream *standard-output*)
                                           (parents t)
                                           (children t)
                                           (landscape nil))
  (let ((types-visited (make-hash-table))
        (type-id-table (make-hash-table))
        (index 1000))
    (dolist (type-name type-name-list)
      (when (gethash type-name types-visited)
        (setf (gethash type-name types-visited) nil))
      (setf types-visited (type-traversal type-name
                                          types-visited
                                          :parents parents
                                          :children children)))

    ;; it appears that margin specifies inches
    (format stream "digraph concept_type_hierarchy {~%")
    (format stream "  graph [rankdir=\"~:[BT~;RL~]\"];~%" landscape)
    (format stream "  node [shape=box,color=snow3,width=0,height=0, margin=.03, fontname=Helvetica];~%")
    (format stream "  edge [arrowhead=none,color=steelblue];~%")
    ;; arrowhead=  open, vee, normal

    ;; add node structures
    (maphash #'(lambda (super-type v)
                 (declare (ignore v))
                 (unless (equal (label super-type) '%)
                   (setf (gethash super-type type-id-table) index)
                   (format stream " type~a [label=\"~a\"]~%" index (label super-type)))
                 (incf index))
             types-visited)

    ;; add edges
    (maphash #'(lambda (supertype v)
                 (declare (ignore v))
                 (let ((subtypes (direct-subtypes supertype)))
                   (dolist (subtype subtypes)
                     (let ((subtype-id (gethash subtype type-id-table))
                           (supertype-id (gethash supertype type-id-table)))
                       ;; all subtypes are not necessarily known
                       ;; exclude bottom node
                       (when (and subtype-id (not (equal (label subtype) '%)))
                         (format stream "  type~a -> type~a;~%" subtype-id supertype-id))))))
             types-visited)
    (format stream "}~%")))


;;; filedir ends with a "/"
;;; graph-name has no "/" or extension
;;; can be used to display .dot files generated by graph-concept-types()
#+swank
(defun display-graph (graph-name &optional (filedir *cgraph-data-directory*))
  (swank:eval-in-emacs
   `(let ((file (format "%s%s" ,filedir ,graph-name)))
      (with-temp-buffer
          (insert-file-contents (format "%s.dot" file) nil nil nil t)
        (compile (format "dot -Tpng %s.dot -o %s.png" file file ))
        (graphviz-dot-preview)))))

#-swank
(defun display-graph (graph-name &optional (filedir *cgraph-data-directory*))
  (declare (ignore graph-name filedir))
  (warn "display-graph requires SWANK/SLIME to be loaded"))

;;; (display-graph "animal" "~/.cgraph/data/")
;;; (display-graph "animal")

(defun redisplay (graph-name)
  (display-graph graph-name *cgraph-data-directory*))


;;; type-name-list is a list of symbols, or a single symbol
(defun graph-concept-types (type-name-list &key (graph-name "type_hierarchy")
                                                (landscape nil))
  "Generate a type diagram for the specified type(es).
   This tool only works when the Graphviz application (www.graphviz.org)
   is installed in /Applications/Graphviz.app "

  (unless (listp type-name-list)
    (setf type-name-list (list type-name-list)))

  (let* ((file-dir (format nil "~a.cgraph/data/" (namestring (user-homedir-pathname))))
         (file-name (format nil "~a~a.dot" file-dir graph-name)))

    (when (every #'(lambda (c) (get-concept-type c))
                 type-name-list)
      (with-open-file
          (stream file-name :direction :output :if-exists :supersede)
        (generate-concept-type-digraph :type-name-list type-name-list
                                       :stream stream
                                       :parents t
                                       :children t
                                       :landscape landscape))
      (display-graph graph-name file-dir))
    file-name))



;;; elisp function needed for graphing from minibuffer
#+swank
(eval-when (:load-toplevel :execute)
  (swank::eval-in-emacs
   '(defun graph-types (concept-types)
      "draw a graph of the types around the supplied concept types"
      (interactive "swhat concept type(s): ")
      ;;(message "entered %s" concepts)
      (eval-in-repl  (format "(graph-concept-types '%s)" concept-types)))))


;; (swank::eval-in-emacs
;;  '(defun graph-types (arg1 arg2)
;;    (interactive "p\nsconcept(s): ")
;;    (let* ((lscape (cond ((= arg1 1) nil)
;;                         (t t))))
;;      ;;(message (format "(graph-concept-types '%s :landscape %s)" arg2 lscape))
;;      (eval-in-repl  (format "(graph-concept-types '%s :landscape %s)" arg2 lscape)))))


;; (swank::eval-in-emacs
;;  '(defun graph-types (concepts)
;;    (interactive "P\nsconcept(s): ")
;;    (eval-in-repl  (format "(graph-concept-types '%s)" concepts))))
